name: Pentest-Tools.com Scans

on:
    push:
        branches: ["main"]

        # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        inputs:
            url:
                type: string
                description: The URL to scan
                required: true
            pr-id:
                type: string
                description: PR ID
                required: true

jobs:
    test_light_scan:
        runs-on: ubuntu-latest
        name: Run a light scan, no API key needed
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Actual PTT light test
              uses: pentesttoolscom/pentesttools-github-action@master
              id: ptt
              with:
                  target: ${{ steps.deployment.outputs.page_url || 'https://resurse.dev' }}
                  format: text
                  fail: medium
            - name: Check the light output
              run: echo "The light report ${{ steps.ptt.outputs.result }}

    test_deep_scan:
        runs-on: ubuntu-latest
        name: Run a manual deep scan. You will need a suitable API key
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Actual PTT deep test
              uses: pentesttoolscom/pentesttools-github-action@master
              id: ptt
              with:
                  target: ${{ inputs.url || 'https://resurse.dev' }}
                  format: text
                  fail: medium
                  type: deep
                  key: ${{ secrets.PTT_API_KEY }}
            - name: Check the deep output
              run: echo "The deep report ${{ steps.ptt.outputs.result }}"

    test_manual_workflow:
        runs-on: ubuntu-latest
        name: Should Pass -- Github Action runs manually
        if: github.event_name == 'workflow_dispatch'
        steps:
            # To use this repository's private action,
            # you must check out the repository
            - name: Checkout
              uses: actions/checkout@v4
            - name: Actual test
              uses: ./ # Uses an action in the root directory
              id: ptt
              with:
                  target: https://pentest-ground.com:81
                  format: text
                  fail: low
            # Use the output
            - name: Check the output
              run: echo "The report ${{ steps.ptt.outputs.result }}"

    test_published_action:
        name: Test that our published Github Action works
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Actual test - dry
              uses: ./
              id: ptt
              with:
                  target: https://pentest-ground.com:81
                  format: text
                  fail: none
                  type: deep
                  key: ${{ secrets.PTT_API_KEY }}
            - name: Check the output
              run: echo "The report ${{ steps.ptt.outputs.result }}"
            - name: Actual test - using action
              uses: pentesttoolscom/pentesttools-github-action@master
              id: ptt
              with:
                  target: https://pentest-ground.com:81 # Has to be accessible to our scanners: https://pentest-tools.com/whitelist-ipv4.txt
                  format: text
                  fail: none
                  type: deep
                  key: ${{ secrets.PTT_API_KEY }}
            - name: Print the output
              run: echo "The report ${{ steps.ptt.outputs.result }}"
