name: Greetings

permissions:
    contents: read
    issues: write
    pull-requests: write

on:
    pull_request:
        types:
            - opened
    issues:
        types:
            - opened

jobs:
    greeting:
        name: Greet First-Time Contributors
        runs-on: ubuntu-latest

        steps:
            - uses: actions/first-interaction@v3.0.0
              with:
                  issue-message: |
                      # Issue Message with Markdown

                      Viorel thanks you for contributing your first issue! :)
                  pr-message: |
                      # PR Message with Markdown

                      Viorel thanks you for contributing your first Pull Request! :)
